M48
; DRILL file {KiCad 7.0.7} date 2023 September 18, Monday 19:37:44
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-09-18T19:37:44-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.400
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.000
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C1.200
%
G90
G05
T1
X153.9Y-50.3
X165.6Y-50.3
T2
X153.9Y-52.425
X164.2Y-52.425
T3
X153.9Y-48.725
X153.9Y-55.225
X164.2Y-48.725
X164.2Y-55.225
T0
M30
